# Header
menu:
  archives: /archives
  about: /about

toc:
  maxdepth: 3
  class: toc
  slugify: transliteration
  decodeEntities: false
  anchor:
    position: after
    symbol: '####'
    style: header-anchor
