# Header
menu:
  # archives: /archives
  about: /about


# avator
avatar: img/avatar.jpg

# sidebar
toc:
  maxdepth: 3
  class: toc
  slugify: transliteration
  decodeEntities: false
  anchor:
    position: after
    symbol: '####'
    style: header-anchor
